server:
  port: 8082              # ðŸ”¹ Doit correspondre au containerPort du Deployment
  address: 0.0.0.0        # ðŸ”¹ Ã‰coute sur toutes les interfaces rÃ©seau

spring:
  application:
    name: springboot-app   # ðŸ”¹ MÃªme nom que dans le Deployment et Service

  datasource:
    url: jdbc:mysql://mysql-container:3306/gestiondb?useSSL=false&serverTimezone=UTC
    username: root
    password: root123

  profiles:
    active: prod


