services:
  mysql:
    image: mysql:8.0
    container_name: gestion-projet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_projet_db
    ports:
      - "3307:3306"
    networks:
      - gestion-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-app:
    build: .
    container_name: gestion-projet-app
    ports:
      - "9090:8080"  # Port 9090 pour Ã©viter les conflits
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: gestion_projet_db
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gestion-network

networks:
  gestion-network:
    driver: bridge