global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus server itself
  - job_name: 'spring-app'
    metrics_path: '/GestionEvenement/actuator/prometheus'  # Custom context path
    static_configs:
      - targets: ['spring-app:8082']  # Use the Docker container name and internal port
