apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app   # ğŸ”¹ doit correspondre au label du Deployment
  ports:
    - protocol: TCP
      port: 8082          # ğŸ”¹ port interne du service
      targetPort: 8082    # ğŸ”¹ port du conteneur
      nodePort: 30000     # ğŸ”¹ port exposÃ© sur le nÅ“ud Kubernetes (30000-32767)
