global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gestion-evenement-service'
    metrics_path: '/GestionEvenement/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'gestion-evenement-service'
  
  - job_name: 'salle-service'
    metrics_path: '/GestionSalle/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          application: 'salle-service'
  
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8089']
        labels:
          application: 'api-gateway'